# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsnok < Formula
  desc "wget with threads and progress bar"
  homepage "https://github.com/jlentink/wsnok"
  version "0.0.3"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jlentink/wsnok/releases/download/0.0.3/wsnok_darwin_arm64.tar.gz"
      sha256 "e2bd0aedac6683af4d206ce0410b814adbaac4503a4079ebbc0e399956c3f2a5"

      def install
        bin.install "wsnok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlentink/wsnok/releases/download/0.0.3/wsnok_linux_arm64.tar.gz"
      sha256 "7239bbc1460eec864a9de36b7f19fafa282a267d67f64d759537039d3fdf2852"

      def install
        bin.install "wsnok"
      end
    end
  end
end
